config/routes.rb
Rails.application.routes.draw do

  # CMS administration
  match 'cms_admin' => 'cms_admin/cms_pages#index'

  namespace 'cms_admin' do
    resources :cms_pages do
      resources :cms_contents, :only => [:create]
    end
    resources :cms_contents, :only => [:create, :destroy]
  end

  # Generic match
  match '/:page_url' => 'cms#show', :constraints => { :page_url => /([a-z]|[0-9]|-|_|\/)+/ }, :as => "cms_page"
  
end

app/models/cms_content.rb
class CmsContent < ActiveRecord::Base

  # Attributes
  attr_accessible :page_id, 
                  :name,
                  :type,
                  :contents
  
  # Relations
  belongs_to :page, :class_name => "CmsPage"
  has_many :cms_localizations, :autosave => true
  
  # Validations
  validates :name, :presence => true, :format => { :with => /^([a-z]|-|_)+$/ }
  validates_uniqueness_of :name, :scope => :page_id
  # validates :page, :presence => true
  # TODO : validate uniqueness of couple name x page
  
  # Scopes and queries
  scope :global, where(:page_id => nil).includes(:cms_localizations)
  scope :for_page, lambda{|page| where(:page_id => page.id).includes(:cms_localizations)}
  
  # Get/set the contents seamlessly in the linked database
  def contents=(contents_hash)
    # Create/set the cms_localizations
    contents_hash.each_pair do |language, content|
      existing_localization = CmsLocalization.find_by_cms_content_id_and_language(self.id, language)
      if existing_localization
        existing_localization.content = content
        throw "Error updating localization :#{existing_localization.errors}" unless existing_localization.save
      else
        cms_localizations.build(:language => language, :content => content)
      end 
    end    
  end
  
  def contents
    content_hash = Hash.new
    
    # Get the cms_localizations
    cms_localizations.each do |localization|
      content_hash[localization.language.to_sym] = localization.content
    end
    
    return content_hash
  end
  
  def localization(language)
    cms_localizations.find_by_language(language).content
  end
  
    
end

app/models/cms_file.rb
class CmsFile < ActiveRecord::Base
  # # Attributes
  # has_attached_file :file
  # attr_accessible :file
  # 
  # # Validations
  # validates :file, :presence => true
end

app/models/cms_localization.rb
class CmsLocalization < ActiveRecord::Base

  # Attributes
  attr_accessible :content, :language
  
  # Relations
  belongs_to :cms_content
  
  # Validations
  validates_uniqueness_of :language, :scope => :cms_content_id
  validates_presence_of :language
  
  # Scopes and queries
  scope :global, where(:page_id => nil)
  scope :for_page, lambda{|page| where(:page_id => page.id)}
    
end

app/models/cms_page.rb
class CmsPage < ActiveRecord::Base

  # Attributes
  attr_accessible :parent_page, 
                  :name,
                  :url,
                  :layout

  # Relations
  has_many :cms_contents, :foreign_key => "page_id"
  belongs_to :parent_page, :class_name => "CmsPage"
  # TODO : Not mandatory, handle removal
  
  # Validations
  validates :url, :format => { :with => /^([a-z]|[0-9]|-|_|\/)*$/ }
  validates :name, :presence => true, :uniqueness => true, :format => { :with => /^([a-z]|-|_)+$/ }
  # TODO : validate parent_page/url couple is unique


  # Recursive method to get all the content of a page. Can surely be optimized
  # Can also be better written ([list of contents].to_content_hash)
  def to_content(existing_contents = {})    
    # Get the content for this page
    add_contents_to!(cms_contents, existing_contents)
    
    # Add the content of the parent page
    if parent_page
      return parent_page.to_content(existing_contents)
    # Or returns it merged with the global parameters
    else
      return add_contents_to!(CmsContent.global, existing_contents)
    end
  end
  
  def self.global_content
    return CmsContent.global.inject({}){ | acc, content | acc[content.name.to_sym] = content ; acc }
  end

  def to_s
    name
  end
  
  private 
  
  def add_contents_to!(source, dest)
    source.each do |cms_content|
      key = cms_content.name.to_sym
      dest[key] = cms_content unless dest.has_key?(key)
    end
    return dest
  end
    
end

app/controllers/cms_admin/cms_admin_controller.rb
class CmsAdmin::CmsAdminController < ApplicationController
  layout "cms_admin"
  before_filter :cms_check_authentication
  
  private
  
  def cms_check_authentication
    authenticate_or_request_with_http_basic do |username, password|
      username == Microcms.config.username && password == Microcms.config.password
    end
  end
end

app/controllers/cms_admin/cms_contents_controller.rb
class CmsAdmin::CmsContentsController < CmsAdmin::CmsAdminController

  # Only action for create and update
  def create
    @content = CmsContent.find params[:id] if params[:id]
    
    if @content
      @content.attributes = params[:cms_content]
    else
      @content = CmsContent.new(params[:cms_content].merge(:page_id => params[:cms_page_id]))
    end
      
    if @content.save
      flash[:notice] = "Content successfully saved."
    else
      flash[:error] = "The content couldn't be saved:\n#{@content.errors.full_messages.join('\n')}"
    end
    redirect_to request.referer || cms_admin_cms_pages_path
  end
  
  def destroy
    @content = CmsContent.find params[:id]
    unless @content.destroy
      flash[:error] = "The content couldn't be deleted."
    end
    redirect_to request.referer || cms_admin_cms_pages_path
  end  
end

app/controllers/cms_admin/cms_pages_controller.rb
class CmsAdmin::CmsPagesController < CmsAdmin::CmsAdminController

  before_filter :load_page

  def index
    @contents = CmsContent.global
  end
  
  def edit
    @page = CmsPage.find params[:id]
    @contents = @page.to_content.values
  end

  # POST
  def create
    @page = CmsPage.new(params[:cms_page])
    if @page.save
      flash[:notice] = "Page successfully created"
      redirect_to edit_cms_admin_cms_page_url(@page)
    else
      flash[:error] = "Page couldn\'t be created:\n#{@page.errors.full_messages.join('\n')}"
      redirect_to request.referer || cms_admin_cms_pages_url
    end
  end

  # PUT
  def update
    @page = CmsPage.find(params[:id])
    if @page.update_attributes(params[:cms_page])
      flash[:notice] = "Page successfully updated"
    else
      flash[:error] = "Page couldn\'t be updated:\n#{@page.errors.full_messages.join('\n')}"
    end
    redirect_to edit_cms_admin_cms_page_url(@page)
  end
  
  # DELETE
  def destroy
    @page = CmsPage.find(params[:id])
    @page.destroy
    flash[:notice] = "Page successfully deleted"
    redirect_to cms_admin_cms_pages_url
  end
  
  private
  
  def load_page
    @pages = CmsPage.all
    @new_page = CmsPage.new
    @new_content = CmsContent.new
  end
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  
  def show
    # Get the page
    @page = CmsPage.find_by_url(params[:page_url])

    # 404 if not found
    render :file => "public/404.html", :status => 404, :layout => false and return unless @page
    
    # Get the dynamic content
    @cms_page_content = @page.to_content

    # Render the corresponding view
    unless @page.layout.nil? || @page.layout.empty?
      render "cms/#{@page.name}", :layout => @page.layout
    else
      render "cms/#{@page.name}"
    end
  end

end

app/views/cms_admin/cms_contents/_cms_content.html.erb
<% page_id ||= nil %>
<div class="content <%= 'other_page' if page_id != cms_content.page_id %>">
  <h5><%= cms_content.name %></h5>
  
  <% cms_content.contents.each_pair do |locale, translation| %>
    <p>[<%=locale%>] <%= truncate (strip_tags translation) %></p>
  <% end %>
  
  <%= link_to "Edit", "#", :class => "edit_content_link button", :content_id => cms_content.id %>
  <%= link_to "Delete", [:cms_admin, cms_content], :class => "button", :method => :delete, :confirm => "Are you sure you want to delete this content?" %>

  <%= render :partial => 'cms_admin/cms_contents/fields', :locals => {:cms_content => cms_content} %>
</div>

app/views/cms_admin/cms_contents/_fields.html.erb
<div class="cms_content_fields hidden" content_id="<%= cms_content.id %>" form_url="<%= cms_admin_cms_contents_path(:id => cms_content.id) %>">
  <div class="content_name"><%= cms_content.name %></div>

  <% I18n.available_locales.each do |locale| %>
    <div class="content_translation" locale="<%= locale %>">
      <%= cms_content.contents[locale] %>
    </div>
  <% end %>
</div>

app/views/cms_admin/cms_contents/_form.html.erb
<% page_id ||= nil %>
<% create_form_url = page_id ? cms_admin_cms_page_cms_contents_path(:cms_page_id => page_id) : cms_admin_cms_contents_path %>

<a href="#" id="new_content" class="button" form_url = "<%= create_form_url %>">New content</a>

<div class="content_form">
  <!-- <h3 class="new_content">New content for this page</h3>
  <h3 class="edit_content">Edit <span class="content"></span> content for this page</h3> -->

  <%= form_for cms_content, :url => create_form_url, :html => {:id => "content_edition_form"} do |f| %>

    <div id="cms_content_name">
      Name : 
      <%= f.text_field :name, :id => "content_name" %>
    </div>

    <% I18n.available_locales.each do |locale| %>
      <a href="#" class="show_locale" locale="<%= locale %>"><%= locale %></a>
    <% end %>

    <% I18n.available_locales.each do |locale| %>
      <div class="locale_block" locale="<%= locale %>">
        <%= text_area_tag "cms_content[contents][#{locale}]", cms_content.contents[locale], :class => "editor" %>
      </div>
    <% end %>
            
    <span class="new_content"><%= f.submit "Create" %></span>
    <span class="edit_content"><%= f.submit "Update" %></span>

  <% end%>
</div>

app/views/cms_admin/cms_pages/_menu.html.erb
<ul class="tabs">
  <li><%= link_to "Global content", cms_admin_cms_pages_path, :class => ("active" unless @page) %></li>
  <% @pages.each do |page| %>
    <li>
      <%= link_to page, edit_cms_admin_cms_page_url(page), :class => ("active" if @page && @page == page) %>
    </li>
  <% end %>  
  <li style="float:right">
    <a href="#" id="new_page">New</a>
  </li>
</ul>

<div id="new_page_form" class="hidden">
  <h3 class="left">New page</h3>
  <%= form_for [:cms_admin, @new_page] do |f| %>
    <p>
      <%= f.text_field :name, :placeholder => "Name" %>

      <%= f.collection_select :parent_page_id, @pages, :id, :name, {:include_blank => 'Parent'} %>
      <%= f.submit "New" %>
    </p>
  <% end %>
	<hr/>
</div>

app/views/cms_admin/cms_pages/edit.html.erb
<% content_for :title, "#{@page} page" %>

<%= content_for :content_list do %>
  <div id="edit_cms_page">

    <h3>Edit page</h3>
    <%= form_for @page, :url =>cms_admin_cms_page_path(@page), :method => :put do |f| %>
      <p>
        Name :
        <%= f.text_field :name %>
      </p>
      <p>
        Parent page:
        <%= f.collection_select :parent_page_id, @pages, :id, :name, {:include_blank => 'None'} %>
      </p>
      <p>
        Url:
        <%= f.text_field :url %>
      </p>
      <p>
        Layout:
        <%= f.text_field :layout %>
      </p>
      <%= f.submit "Save" %>
      <%= link_to "Delete", cms_admin_cms_page_path(@page), :class => "button", :method => :delete, :confirm => "Are you sure you want to delete this page?" %>

    <% end %>
  </div>
  
  <h3>Edit Contents</h3>
  <% @contents.each do |content| %>
    <%= render content %>
  <% end %> 
<% end %>

<%= content_for :content_edition do %>
  <%= render :partial => 'cms_admin/cms_contents/form', :locals => {:cms_content => @new_content, :page_id => @page.id}%>
<% end %>

app/views/cms_admin/cms_pages/index.html.erb
<% content_for :title, "global content" %>

<%= content_for :content_list do %>
  <h3>Contents</h3>
  <% @contents.each do |content| %>
    <%= render content %>
  <% end %>
<% end %>

<%= content_for :content_edition do %>
  <%= render :partial => 'cms_admin/cms_contents/form', :locals => {:cms_content => @new_content}%>
<% end %>

app/views/layouts/cms_admin.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>uCMS | <%= yield(:title) %></title>
  <!-- <meta name="description" content=""> -->
  <!-- <meta name="author" content=""> -->
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
  <%= stylesheet_link_tag "cms_admin/base" %>
  <%= stylesheet_link_tag "cms_admin/skeleton" %>
  <%= stylesheet_link_tag  "cms_admin/layout" %>

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="images/cms_admin/favicon.ico">
	<link rel="apple-touch-icon" href="images/cms_admin/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/cms_admin/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/cms_admin/apple-touch-icon-114x114.png">

</head>
<body>



	<!-- Primary Page Layout
	================================================== -->

	<!-- Delete everything in this .container and get started on your own site! -->

	<div class="container">
		<div class="sixteen columns">
			<h1 class="remove-bottom" style="margin-top: 40px">uCMS</h1>
      <hr/>
      <div id="menu">
        <%= render :partial => "cms_admin/cms_pages/menu" %>
      </div>
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      <%= yield %>
		</div>

    <div class="row">
  		<div class="five columns alpha" id="content_list">
          <%= yield :content_list %>        
      </div>

  		<div class="eleven columns omega" id="content_edition">
          <%= yield :content_edition %>
  		</div>
  	</div>

	</div><!-- container -->


	<!-- JS
	================================================== -->
	<%= javascript_include_tag  "cms_admin/jquery.min.js", "ckeditor/ckeditor.js", "ckeditor/adapters/jquery.js", "cms_admin/cms_admin.js" %>

<!-- End Document
================================================== -->
</body>
</html>%        